const NOTIFICATION_TYPES = {
  LOW_STOCK: 'LOW_STOCK',
  PENDING_SHIPMENT: 'PENDING_SHIPMENT',
  STOCK_IN: 'STOCK_IN',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
};

export default NOTIFICATION_TYPES;
